### ISSUE TITLE
Der Bot ist defekt und twittert Corona-Verschwörungstheorien

### ISSUE THREAD

**Issue by loelkes** [schlind/Karlsruher#1]
Hallo @schlind 

der Bot ist defekt. Gestern hat der Karlsruher Bot folgendes getwittert:

<img width="589" alt="Screenshot 2021-01-11 at 08 59 39" src="https://user-images.githubusercontent.com/231909/104157542-a4121300-53eb-11eb-9396-99cac2ba317a.png">

In der Beschreibung (`karlsruher.md`) des Bots steht:

> [...] der Karlsruher ist ein Roboter, der automatisch und ohne redaktionelle Einflußnahme Tweets seiner Follower retweetet. Für Inhalte sind so ausschließlich die Urheber der jeweiligen Tweets verantwortlich. [...]

Offensichtlich ist das nicht der Fall und ich gehe nicht davon aus, dass das gehackt wurde. Wenn du auf Twitter deine eigene Meinung kundtun möchtest, dann mach es mit deinem eigenen Account. Du sprichst nicht für Karlsruhe und zerstörst damit ein schönes und altbekanntes Werkzeug für die meistens von uns.

Meiner Meinung nach ist die Zeit gekommen, dass du den Bot an jemand anderes, zum Beispiel ein Kollektiv, eine Initiative oder einen Verein, übergibst. Danke, dass du dich bis jetzt darum gekümmert hast!

Grüße
Christian

**Comment by RagingSquirrel** [comment]
Dem Issue von loelkes kann ich nur zustimmen. 
Auch sehe ich dringend Handlungsbedarf!

**Comment by loelkes** [comment]
Ich habe auch einen Fork des Repos gemacht. Selbst wenn das hier gelöscht wird oder auf privat/versteckt geschaltet wird bleibt der Fork bestehen.

**Comment by schlind** [comment]
Christian, ganz zuerst für Dein oder unser Publikum: Wir kennen uns nicht und sind uns zuvor nie begegnet. Das ist Deine erste Kontaktaufnahme in meine Richtung. 

Lass mich raten, Du bist Richter und Henker? Dein Bugreport liest sich nämlich wie eine Anklage, Verurteilung und Maßregelvollzug in einem. Hattest Du den Delinquenten schon zweifelsfrei identifiziert oder war das gerade nicht so wichtig? Wolltest Du mich nach dem Erschießen dann noch was fragen? Habe wohl gerade nochmal Glück gehabt, dass wir hier nur im Internet sind. 

Doch zum Kern Deines Anliegens, dafür sind wir jetzt hier. Die hier angebotene Software ist für Retweets verantwortlich und wenn ich alles richtig gelesen habe, bezieht sich Deine Fehlermeldung nicht auf genau diese Funktion sondern auf anderweitige, direkte Nutzung des Accounts. Es tut mir leid, eine solche Nutzung ist kein Defekt, den ich hier beheben könnte. Der Account ist auf seiner Plattform per DM zu erreichen. Darum hat der Accountbetreiber auch auf mein Bitten per DM die Verlinkung auf mein Repository aus dem Profil entfernt und damit sind unsere Möglichkeiten hier dann auch schon vollkommen ausgeschöpft. 

Ich freue mich über jeden Fork und qualifiziertes Feedback zu meinem Code, damit ich davon lernen kann. Ebenso bitte ich um Verständnis dafür, dass ich Anliegen über Technisches hinaus, Mutmaßungen, persönliche Anschuldigungen oder Therapierungsversuche usw., in öffentlichen Foren für prinzipiell als komplett falsch verortet halte. 
Nochmal, die Art und Weise, mit der Du einer Dir fremden Person, also mir, hier öffentlich zur Begrüßung begegnest, ist für diese Plattform absolut untypisch und ich bezweifle, dass sie gegen die Community-Regeln validiert. 

Ich hoffe, ich konnte Dir irgendwie weiterhelfen.

Danke für Dein Engagement,
Sascha

**Comment by DrLuke** [comment]
Interessant. Du schreibst hier einerseits so, als würdest du den Twitter-Bot nicht betreiben, stellst es aber [hier](https://github.com/schlind/Karlsruher/blob/master/karlsruher.md#verantwortung-und-ansprechpartner) so dar, als wärst du der/die Betreiber:in. Also was nun?

**Comment by schlind** [comment]
Mit Verlaub, kennen wir uns? Hast Du gerade keine anderen Sorgen? Warum belästigst Du mich? Was versprichst Du Dir davon, Dich in einem Bugtracker noch an einer bereits abgeschlossenen, öffentlichen Hetzjagt zu beteiligen? 

Ich denke, ich melde diese Übergriffe hier jetzt doch mal an GitHub.

**Comment by DrLuke** [comment]
> Mit Verlaub, kennen wir uns? 

Hoffentlich nicht!

>Hast Du gerade keine anderen Sorgen? 

Das geht dich, mit Verlaub, nichts an.

>Warum belästigst Du mich? Was versprichst Du Dir davon, Dich in einem Bugtracker noch an einer bereits abgeschlossenen, öffentlichen Hetzjagt zu beteiligen?

Schade, dass du Kritik als Belästigung und Hetzjagd wahrnimmst.

> Ich denke, ich melde diese Übergriffe hier jetzt doch mal an GitHub.

Ok.

**Comment by karkla** [comment]
Lieber Sascha,

hast du noch Zugriff auf den Account? Würdest du den Account in diesem Fall freundlicherweise übergeben, damit er im Sinne der ursprünglichen Idee und der Follower weitergeführt werden kann? Würde mich freuen wenn du dich hierzu eventuell durchringen könntest. Setze doch bitte in diesem Falle kurz das PW zurück und übergib ihn an jemanden vertrauenswürdigen. Der Account hat ja eigentlich mit der Coronasache nichts zu tun, oder?

Viele Grüße
